### ISSUE TITLE
EXE Program Issue

### ISSUE THREAD

**Issue by velvetbyrne** [fenhl/json-to-mse#23] opened 2020-06-11 15:05 UTC
The win64 and win32 EXE programs won't launch. Hopefully, the issue can be fixed soon

**Comment by fenhl** [comment] 2020-06-11 15:13
I can't reproduce this issue. What version of Windows are you using?

**Comment by fenhl** [comment] 2020-08-03 17:47
Closing until further information is provided.

**Closed as completed by fenhl** 2020-08-03 17:47 UTC
Labels: question
